.TH "Src Directory Reference" 3 "Fri Mar 9 2018" "Version 1.2" "DoxyTemp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbluetooth\&.c\fP"
.br
.RI "\fBbluetooth\&.c\fP file, complements \fBmain\&.c\fP and "
.ti -1c
.RI "file \fBcrc\&.c\fP"
.br
.ti -1c
.RI "file \fBdisplay\&.c\fP"
.br
.RI "Display handles the initialization of the display and communication\&. "
.ti -1c
.RI "file \fBgpio\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBrtc\&.c\fP"
.br
.ti -1c
.RI "file \fBsetuartrtc\&.c\fP"
.br
.RI "setUartRtc is initializing the clock to a value set by UART "
.ti -1c
.RI "file \fBspi\&.c\fP"
.br
.ti -1c
.RI "file \fBstm32f3xx_hal_msp\&.c\fP"
.br
.ti -1c
.RI "file \fBstm32f3xx_it\&.c\fP"
.br
.RI "Interrupt Service Routines\&. "
.ti -1c
.RI "file \fBsystem_stm32f3xx\&.c\fP"
.br
.RI "CMSIS Cortex-M4 Device Peripheral Access Layer System Source File\&. "
.ti -1c
.RI "file \fBtelldus\&.c\fP"
.br
.RI "Telldus file, complements \fBmain\&.c\fP and\&. "
.ti -1c
.RI "file \fBtim\&.c\fP"
.br
.ti -1c
.RI "file \fBusart\&.c\fP"
.br
.in -1c
