.TH "Src/bluetooth.c" 3 "Fri Mar 9 2018" "Version 1.2" "DoxyTemp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/bluetooth.c \- \fBbluetooth\&.c\fP file, complements \fBmain\&.c\fP and  

.SH SYNOPSIS
.br
.PP
\fC#include 'bluetooth\&.h'\fP
.br
\fC#include 'gpio\&.h'\fP
.br
\fC#include 'usart\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'setuartrtc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitBluetooth\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBbluetooth\&.c\fP file, complements \fBmain\&.c\fP and 


.PP
\fBAuthor:\fP
.RS 4
Johan Hanssen 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
28-February-2018 The code for initializing the bluetooth module 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void initBluetooth ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for DoxyTemp from the source code\&.
