.TH "Src/main.c" 3 "Fri Mar 9 2018" "Version 1.2" "DoxyTemp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'stm32f3xx_hal\&.h'\fP
.br
\fC#include 'crc\&.h'\fP
.br
\fC#include 'rtc\&.h'\fP
.br
\fC#include 'spi\&.h'\fP
.br
\fC#include 'tim\&.h'\fP
.br
\fC#include 'usart\&.h'\fP
.br
\fC#include 'gpio\&.h'\fP
.br
\fC#include 'stdbool\&.h'\fP
.br
\fC#include 'telldus\&.h'\fP
.br
\fC#include 'display\&.h'\fP
.br
\fC#include 'setuartrtc\&.h'\fP
.br
\fC#include 'bluetooth\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSystemClock_Config\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureCallback\fP (TIM_HandleTypeDef *\fBhtim2\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.ti -1c
.RI "void \fB_Error_Handler\fP (char *file, int line)"
.br
.RI "This function is executed in case of error occurrence\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "RTC_HandleTypeDef \fBhrtc\fP"
.br
.ti -1c
.RI "RTC_TimeTypeDef \fBsTime\fP"
.br
.ti -1c
.RI "RTC_DateTypeDef \fBsDate\fP"
.br
.ti -1c
.RI "uint8_t \fBshowtime\fP [10] = {0}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _Error_Handler (char * file, int line)"

.PP
This function is executed in case of error occurrence\&. 
.PP
\fBParameters:\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef * htim2)"

.SS "int main (void)"

.SS "void SystemClock_Config (void)"
System Clock Configuration Initializes the CPU, AHB and APB busses clocks
.PP
Initializes the CPU, AHB and APB busses clocks
.PP
Configure the Systick interrupt time
.PP
Configure the Systick
.SH "Variable Documentation"
.PP 
.SS "RTC_HandleTypeDef hrtc"
File Name : \fBmain\&.c\fP Description : Main program body
.PP
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2018 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SS "RTC_DateTypeDef sDate"

.SS "uint8_t showtime[10] = {0}"

.SS "RTC_TimeTypeDef sTime"

.SH "Author"
.PP 
Generated automatically by Doxygen for DoxyTemp from the source code\&.
