.TH "Src/spi.c" 3 "Fri Mar 9 2018" "Version 1.2" "DoxyTemp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/spi.c
.SH SYNOPSIS
.br
.PP
\fC#include 'spi\&.h'\fP
.br
\fC#include 'gpio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_SPI2_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SPI_MspInit\fP (SPI_HandleTypeDef *spiHandle)"
.br
.ti -1c
.RI "void \fBHAL_SPI_MspDeInit\fP (SPI_HandleTypeDef *spiHandle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SPI_HandleTypeDef \fBhspi2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HAL_SPI_MspDeInit (SPI_HandleTypeDef * spiHandle)"
SPI2 GPIO Configuration PF9 ------> SPI2_SCK PB14 ------> SPI2_MISO PB15 ------> SPI2_MOSI
.SS "void HAL_SPI_MspInit (SPI_HandleTypeDef * spiHandle)"
SPI2 GPIO Configuration PF9 ------> SPI2_SCK PB14 ------> SPI2_MISO PB15 ------> SPI2_MOSI
.SS "void MX_SPI2_Init (void)"

.SH "Variable Documentation"
.PP 
.SS "SPI_HandleTypeDef hspi2"
File Name : SPI\&.c Description : This file provides code for the configuration of the SPI instances\&.
.PP
This notice applies to any and all portions of this file that are not between comment pairs USER CODE BEGIN and USER CODE END\&. Other portions of this file, whether inserted by the user or by software development tools are owned by their respective copyright owners\&.
.PP
COPYRIGHT(c) 2018 STMicroelectronics
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.IP "1." 4
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "2." 4
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "3." 4
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DoxyTemp from the source code\&.
