.TH "STM32F3xx_System_Private_Defines" 3 "Fri Mar 9 2018" "Version 1.2" "DoxyTemp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F3xx_System_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   ((uint32_t)8000000)"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   ((uint32_t)8000000)"
.br
.ti -1c
.RI "#define \fBVECT_TAB_OFFSET\fP   0x0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HSE_VALUE   ((uint32_t)8000000)"
Default value of the External oscillator in Hz\&. This value can be provided and adapted by the user application\&. 
.SS "#define HSI_VALUE   ((uint32_t)8000000)"
Default value of the Internal oscillator in Hz\&. This value can be provided and adapted by the user application\&. 
.SS "#define VECT_TAB_OFFSET   0x0"
< Uncomment the following line if you need to relocate your vector Table in Internal SRAM\&. Vector Table base offset field\&. This value must be a multiple of 0x200\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DoxyTemp from the source code\&.
