.TH "STM32F3xx_System_Private_Variables" 3 "Fri Mar 9 2018" "Version 1.2" "DoxyTemp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F3xx_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 8000000"
.br
.ti -1c
.RI "const uint8_t \fBAHBPrescTable\fP [16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.ti -1c
.RI "const uint8_t \fBAPBPrescTable\fP [8] = {0, 0, 0, 0, 1, 2, 3, 4}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "const uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"

.SS "const uint8_t APBPrescTable[8] = {0, 0, 0, 0, 1, 2, 3, 4}"

.SS "uint32_t SystemCoreClock = 8000000"

.SH "Author"
.PP 
Generated automatically by Doxygen for DoxyTemp from the source code\&.
